"""Two observability signals that share the same `correlation_id`:

    1. structlog JSON logs           — one 'node.start' + one 'node.end' (or
                                        'node.error') per node
    2. OpenTelemetry spans           — one span per node, parented under the
                                        graph-run root span

`correlation_id` is generated by the CLI, propagated through TriageState,
bound to structlog contextvars, and set as an OTel span attribute. That
single ID lets an operator jump from a Discord alert to the log line to the
trace of the exact execution that produced it.

The tracer defaults to console-exporter so evidence is visible with zero
extra infra. Set `PW_OTEL_EXPORTER=otlp` + `PW_OTLP_ENDPOINT=...` to ship
spans to Jaeger/Tempo/etc.
"""

from __future__ import annotations

import functools
import logging
import time
from collections.abc import Callable

import structlog
from opentelemetry import trace
from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk.resources import SERVICE_NAME, Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import (
    BatchSpanProcessor,
    ConsoleSpanExporter,
)

from pipeline_watch.state import TriageState

_configured = False


def configure(
    log_level: str = "INFO",
    exporter: str = "console",
    otlp_endpoint: str | None = None,
) -> None:
    """Idempotent. Safe to call from CLI, tests, or user code."""

    global _configured
    if _configured:
        return
    _configure_tracer(exporter=exporter, otlp_endpoint=otlp_endpoint)
    _configure_structlog(log_level=log_level)
    _configured = True


def _configure_tracer(exporter: str, otlp_endpoint: str | None) -> None:
    resource = Resource.create({SERVICE_NAME: "pipeline_watch"})
    provider = TracerProvider(resource=resource)
    if exporter == "otlp" and otlp_endpoint:
        provider.add_span_processor(
            BatchSpanProcessor(OTLPSpanExporter(endpoint=otlp_endpoint))
        )
    else:
        provider.add_span_processor(BatchSpanProcessor(ConsoleSpanExporter()))
    trace.set_tracer_provider(provider)


def _configure_structlog(log_level: str) -> None:
    structlog.configure(
        processors=[
            structlog.contextvars.merge_contextvars,
            structlog.processors.add_log_level,
            structlog.processors.TimeStamper(fmt="iso"),
            structlog.processors.EventRenamer("event"),
            structlog.processors.JSONRenderer(),
        ],
        wrapper_class=structlog.make_filtering_bound_logger(
            getattr(logging, log_level, logging.INFO)
        ),
        cache_logger_on_first_use=True,
    )


def get_logger(name: str = "pipeline_watch") -> structlog.BoundLogger:
    return structlog.get_logger(name)


def get_tracer(name: str = "pipeline_watch"):
    return trace.get_tracer(name)


def traced_node(fn: Callable[[TriageState], dict]) -> Callable[[TriageState], dict]:
    """Wrap a graph node so it emits one log + one span per invocation.

    The `correlation_id` from state is bound to structlog contextvars for the
    duration of the node call — subsequent logs from libraries in the same
    call chain will carry the same id.
    """

    node_name = fn.__name__
    log = get_logger()
    tracer = get_tracer()

    @functools.wraps(fn)
    def wrapper(state: TriageState) -> dict:
        correlation_id = state.get("correlation_id", "unknown")
        run_id = state.get("run_id", "unknown")

        with tracer.start_as_current_span(f"node.{node_name}") as span:
            span.set_attribute("pw.correlation_id", correlation_id)
            span.set_attribute("pw.run_id", run_id)
            span.set_attribute("pw.node", node_name)

            structlog.contextvars.bind_contextvars(
                correlation_id=correlation_id,
                run_id=run_id,
                node=node_name,
            )
            log.info("node.start")
            t0 = time.perf_counter()
            try:
                result = fn(state)
            except Exception as e:
                elapsed_ms = round((time.perf_counter() - t0) * 1000, 2)
                log.error(
                    "node.error",
                    elapsed_ms=elapsed_ms,
                    error=str(e),
                    error_type=type(e).__name__,
                )
                span.record_exception(e)
                span.set_status(trace.Status(trace.StatusCode.ERROR, str(e)))
                raise
            finally:
                # Clear contextvars so the next node (possibly on the same
                # thread) doesn't inherit stale bindings.
                structlog.contextvars.clear_contextvars()

            elapsed_ms = round((time.perf_counter() - t0) * 1000, 2)
            span.set_attribute("pw.elapsed_ms", elapsed_ms)
            written_keys = list(result.keys()) if isinstance(result, dict) else []
            log.info("node.end", elapsed_ms=elapsed_ms, wrote=written_keys)
            return result

    return wrapper
